### ISSUE TITLE
Port to python 3

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/five.pt#8]
Hi all,

is there any user of five.pt around apart from Plone? Is there anyone willing to port it to python 3?

One of the migration points would be to move away from sourcecodegen, which hopefully, the crew involved in porting restrictedpython can help on that.

/cc @loechel

**Comment by loechel** [comment]
Is five.pt still necessary in Plone 5 and above? I thought there was a native inclusion of Chamelion in Plone now.

But yes we could look at it and try to port it.

**Comment by gforcada** [comment]
Probably not then, so far only Products.CMFPlone depends on it (on setup.py as well as loading its ZCML).

**Comment by sallner** [comment]
@gforcada @loechel  With https://github.com/zopefoundation/Zope/commit/cc059e24c1280bc9eaf077a9adbee1bb4267a7c3 `five.pt` was integrated to Zope 4. Later on this was also ported to use the new `RestictedPython` so that the dependency on `sourcecodegen` was removed. 

This package `five.pt` will be turned into an empty package with ZCML for backwards compatibility.

**Comment by icemac** [comment]
See #9.
